// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually 
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */



  JavaScriptSidebar: [

    {
      type: 'category',
      label: '函数',
      items:[
        { type: 'doc', id: 'Web/JavaScript——函数——立执行函数', label: '立执行函数' },
        { type: 'doc', id: 'Web/JavaScript——函数——箭头函数', label: '箭头函数' },
        { type: 'doc', id: 'Web/JavaScript——函数——函数内部的this对象', label: '函数内部的this对象' },
        { type: 'doc', id: 'Web/JavaScript——函数——函数内部的arguments对象', label: '函数内部的arguments对象' },
        { type: 'doc', id: 'Web/JavaScript——函数——函数的call()和apply()方法', label: '函数的call()和apply()方法' },
        { type: 'doc', id: 'Web/JavaScript——函数——函数的暂时性死区', label: '函数的暂时性死区' },
        { type: 'doc', id: 'Web/JavaScript——函数——函数的默认参数', label: '函数的默认参数' },
        { type: 'doc', id: 'Web/JavaScript——函数——参数收集和参数扩展', label: '参数收集和参数扩展' },

      ]
    },

    {
      type: 'category',
      label: '数组',
      items: [
        { type: 'doc', id: 'Web/JavaScript——数组——数组的本质也是对象', label: '数组的本质也是对象' },
        { type: 'doc', id: 'Web/JavaScript——数组——数组的方法', label: '数组的方法' },
        { type: 'doc', id: 'Web/JavaScript——数组——数组的归并', label: '数组的归并' },
        { type: 'doc', id: 'Web/JavaScript——数组——数组的基础语法', label: '数组的基础语法' },
        { type: 'doc', id: 'Web/JavaScript——数组——数组的排序', label: '数组的排序' },
        { type: 'doc', id: 'Web/JavaScript——数组——新建或转化为数组', label: '新建或转化为数组' },
        { type: 'doc', id: 'Web/JavaScript——数组——Set集合类型', label: 'Set集合类型' },
      ]
    },

    {
      type: 'category',
      label: '对象',
      items: [
        { type: 'doc', id: 'Web/JavaScript——对象——对象的方法', label: '对象的方法' },
        { type: 'doc', id: 'Web/JavaScript——对象——Map映射类型', label: 'Map映射类型' },
        { type: 'doc', id: 'Web/JavaScript——对象——JSON', label: 'JSON' },
        { type: 'doc', id: 'Web/JavaScript——对象——自定义事件', label: '自定义事件' },
        { type: 'doc', id: 'Web/JavaScript——对象——新建对象', label: '新建对象' },
        { type: 'doc', id: 'Web/JavaScript——对象——面向对象', label: '面向对象' },
        { type: 'doc', id: 'Web/JavaScript——对象——对象的getter和setter', label: '对象的getter和setter' },
        { type: 'doc', id: 'Web/JavaScript——对象——对象的语法规则', label: '对象的语法规则' },
        { type: 'doc', id: 'Web/JavaScript——对象——对象的属性特性', label: '对象的属性特性' },
      ]
    },

    {
      type: 'category',
      label: 'WebAPI',
      items: [
        { type: 'doc', id: 'Web/JavaScript——WebAPI——地理定位', label: '地理定位' },
        { type: 'doc', id: 'Web/JavaScript——WebAPI——定时器', label: '定时器' },
        { type: 'doc', id: 'WebJavaScript——WebAPI——桌面通知', label: '桌面通知' },
        { type: 'doc', id: 'Web/JavaScript——WebAPI——自定义事件', label: '自定义事件' },
        { type: 'doc', id: 'Web/JavaScript——WebAPI——Fetch', label: 'Fetch' },
        { type: 'doc', id: 'Web/JavaScript——WebAPI——FileSystemAPI', label: 'FileSystemAPI' },
        { type: 'doc', id: 'Web/JavaScript——WebAPI——iframe', label: 'iframe' },
        { type: 'doc', id: 'Web/JavaScript——WebAPI——LocalStorage', label: 'LocalStorage' },
        { type: 'doc', id: 'Web/JavaScript——WebAPI——URLAPI', label: 'URLAPI' },
      ]
    },

    {
      type: 'category',
      label: 'DOM',
      items: [
        { type: 'doc', id: 'Web/JavaScript——DOM——获取元素', label: '获取元素' },
        { type: 'doc', id: 'Web/JavaScript——DOM——添加元素', label: '添加元素' },
        { type: 'doc', id: 'Web/JavaScript——DOM——删除元素', label: '删除元素' },
      ]
    }

  ],

  ReactSidebar: [

    {
      type: 'doc',
      id: 'Web/React——新建React项目',
      label: '新建React项目'
    },
    {
      type: 'doc',
      id: 'Web/React——使用Vite创建React项目',
      label: '使用Vite创建React项目'
    },
    {
      type: 'doc',
      id: 'Web/React——添加样式',
      label: '添加样式'
    },
    {
      type: 'category',
      label: 'Hooks',
      items: [
        {
          type: 'doc',
          id: 'Web/React——Hooks——Hooks使用规则',
          label: 'Hooks使用规则'
        },
        {
          type: 'doc',
          id: 'Web/React——Hooks——useState()',
          label: 'useState()'
        },
        {
          type: 'doc',
          id: 'Web/React——Hooks——useEffect()',
          label: 'useEffect()'
        },
      ]
    },



  ],



};

export default sidebars;
